from flask import Flask, render_template, request, jsonify, send_file
from password_analyzer import PasswordStrengthAnalyzer
import traceback
import json
import os
from datetime import datetime
import io

app = Flask(__name__)
analyzer = PasswordStrengthAnalyzer()

# Store breach database (expandable)
BREACH_DATABASE = {
    'rockyou': ['password', '123456', 'qwerty', 'admin', 'letmein'],
    'linkedin': ['linkedin123', 'password2012'],
    'adobe': ['adobe123', 'photoshop'],
    'haveibeenpwned': []  # Would connect to API in production
}

@app.route('/')
def index():
    """Render the main page"""
    return render_template('index.html')

@app.route('/analyze', methods=['POST'])
def analyze_password():
    """API endpoint to analyze password"""
    try:
        data = request.get_json()
        password = data.get('password', '')
        
        if not password:
            return jsonify({'error': 'Password cannot be empty'}), 400
        
        # Analyze password
        results = analyzer.analyze(password)
        
        if results:
            # Add breach database check
            breach_results = check_breach_databases(password)
            results['breach_check'] = breach_results
            
            response = {
                'success': True,
                'entropy': results['entropy'],
                'crack_time': results['crack_time'],
                'strength_rating': results['strength_rating'],
                'strength_color': results['strength_color'],
                'strength_level': results['strength_level'],  # For theme switching
                'length_score': results['length']['score'],
                'length_message': results['length']['message'],
                'variety_score': results['variety']['score'],
                'variety_message': results['variety']['message'],
                'patterns_score': results['patterns']['score'],
                'patterns_message': results['patterns']['message'],
                'common_score': results['common']['score'],
                'common_message': results['common']['message'],
                'suggestions': results['suggestions'],
                'total_score': results['total_score'],
                'breach_check': breach_results,
                'timestamp': datetime.now().isoformat()
            }
            return jsonify(response)
        else:
            return jsonify({'error': 'Analysis failed'}), 500
            
    except Exception as e:
        print(f"Error: {traceback.format_exc()}")
        return jsonify({'error': str(e)}), 500

@app.route('/export-report', methods=['POST'])
def export_report():
    """Export analysis as TXT file"""
    try:
        data = request.get_json()
        report_data = data.get('report', {})
        
        # Generate report content
        report_content = generate_report(report_data)
        
        # Create file in memory
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"password_audit_{timestamp}.txt"
        
        return send_file(
            io.BytesIO(report_content.encode('utf-8')),
            mimetype='text/plain',
            as_attachment=True,
            download_name=filename
        )
    except Exception as e:
        return jsonify({'error': str(e)}), 500

def check_breach_databases(password):
    """Check password against multiple breach databases"""
    breaches_found = []
    
    # Check common passwords
    if password.lower() in BREACH_DATABASE['rockyou']:
        breaches_found.append('RockYou (2009) - 32 million passwords')
    
    # Check pattern-based breaches
    if len(password) < 8:
        breaches_found.append('Weak Password Pattern - Common in multiple breaches')
    
    if password.isalpha():
        breaches_found.append('Letters-only pattern - Found in LinkedIn breach (2012)')
    
    if password.isdigit():
        breaches_found.append('Numbers-only pattern - Common in RockYou breach')
    
    # Check for repeated patterns
    if len(set(password)) < 3:
        breaches_found.append('Low entropy pattern - Present in 95% of breach databases')
    
    return {
        'found': len(breaches_found) > 0,
        'count': len(breaches_found),
        'breaches': breaches_found
    }

def generate_report(report_data):
    """Generate formatted report"""
    report = f"""
╔══════════════════════════════════════════════════════════════════╗
║              PASSWORD SECURITY AUDIT REPORT                      ║
║                    GENERATED BY ANALYZER v3.0                     ║
╚══════════════════════════════════════════════════════════════════╝

[+] SCAN INFORMATION
    Date/Time: {report_data.get('timestamp', 'Unknown')}
    Analyzer Version: 3.0 (Enhanced Edition)
    Security Protocols: ACTIVE

[+] PASSWORD ANALYSIS RESULTS
    Strength Rating: {report_data.get('strength_rating', 'Unknown')}
    Entropy: {report_data.get('entropy', 0)} bits
    Estimated Crack Time: {report_data.get('crack_time', 'Unknown')}
    Security Score: {report_data.get('total_score', 0)}/12

[+] DETAILED BREAKDOWN
    Length Check: {report_data.get('length_message', 'N/A')}
    Character Variety: {report_data.get('variety_message', 'N/A')}
    Pattern Analysis: {report_data.get('patterns_message', 'N/A')}
    Common Password: {report_data.get('common_message', 'N/A')}

[+] BREACH DATABASE CHECK
    Breaches Found: {report_data.get('breach_count', 0)}
    {chr(10).join(['    • ' + b for b in report_data.get('breaches', [])]) if report_data.get('breaches') else '    • No known breaches detected'}

[+] SECURITY RECOMMENDATIONS
    {chr(10).join(['    • ' + s for s in report_data.get('suggestions', [])])}

[+] CLASSIFICATION
    This password is considered: {report_data.get('strength_rating', 'Unknown')}
    
    Next Steps:
    • {'Immediately change this password' if report_data.get('strength_level') in ['CRITICAL', 'WEAK'] else 'Monitor this password regularly'}
    • Enable 2FA on associated accounts
    • Never reuse this password across multiple services

[+] REPORT FOOTER
    This report was generated automatically. Keep it secure.
    ═══════════════════════════════════════════════════════════════
    END OF REPORT
    """
    return report

if __name__ == '__main__':
    print("🔐 Starting Enhanced Password Strength Analyzer...")
    print("🌐 Open: http://127.0.0.1:5000")
    print("🎨 Theme: Dynamic (Amber → Green → Red based on password strength)")
    app.run(debug=True, host='127.0.0.1', port=5000)